[package]
name = "sb_workers"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
deno_config.workspace = true
deno_core.workspace = true
deno_http.workspace = true

fs.workspace = true
graph.workspace = true
http_utils.workspace = true

sb_core.workspace = true
sb_event_worker.workspace = true

anyhow.workspace = true
bytes.workspace = true
enum-as-inner.workspace = true
futures-util.workspace = true
hyper_v014.workspace = true
log.workspace = true
once_cell.workspace = true
scopeguard.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
tokio.workspace = true
uuid.workspace = true
