[package]
name = "ext_env"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true

ext_core.workspace = true
ext_node.workspace = true
