[package]
name = "sb_core"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
deno_ast = { workspace = true, features = ["transpiling", "bundler", "cjs", "codegen", "proposal", "react", "sourcemap", "transforms", "typescript", "view", "visit"] }
deno_cache_dir.workspace = true
deno_core.workspace = true
deno_crypto.workspace = true
deno_fetch.workspace = true
deno_fs.workspace = true
deno_graph.workspace = true
deno_http.workspace = true
deno_io.workspace = true
deno_net.workspace = true
deno_npm.workspace = true
deno_permissions.workspace = true
deno_tls.workspace = true
deno_web.workspace = true
deno_websocket.workspace = true
deno_webstorage.workspace = true

base_mem_check.workspace = true
base_rt.workspace = true
deno_manifest.workspace = true

sb_node.workspace = true

anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
bytes.workspace = true
enum-as-inner.workspace = true
faster-hex.workspace = true
fs3.workspace = true
futures.workspace = true
http.workspace = true
httparse.workspace = true
hyper_v014.workspace = true
hyper.workspace = true
import_map.workspace = true
indexmap.workspace = true
libc.workspace = true
log.workspace = true
once_cell.workspace = true
percent-encoding.workspace = true
rand.workspace = true
ring.workspace = true
scopeguard.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing.workspace = true

cache_control = "=0.2.0"
chrono = { version = "=0.4.22", default-features = false, features = ["clock"] }
data-url = "=0.3.0"
encoding_rs = "=0.8.33"
memmem = "0.1"
twox-hash = "=1.6.3"

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true, features = ["knownfolders", "mswsock", "objbase", "shlobj", "tlhelp32", "winbase", "winerror", "winsock2"] }
